[package]
name = "oauth"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
redis.workspace = true

base64 = "0.22.1"
digest = "0.10.7"
rand = "0.8.5"
reqwest = {version = "0.12.7", features = ["rustls-tls-native-roots", "multipart", "json"] }
serde = { version = "1.0.208", features = ["derive"] }
serenity = {version = "0.12.2", default-features = false}
sha2 = "0.10.8"
url = "2.5.2"
