name: Frontend
on: pull_request
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Setup Node.js Environment
        uses: actions/setup-node@main
        with:
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Link Check
        run: pnpm eslint ./frontend/**/*.{ts,tsx}
  format:
    name: Format
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Setup Node.js Environment
        uses: actions/setup-node@main
        with:
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Format Check
        run: pnpm prettier --check .
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Setup Node.js Environment
        uses: actions/setup-node@main
        with:
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Check
        run: pnpm build
